const freshProducts = [
      {
            id: 1,
            name: "Apples",
            description: "Fresh and juicy red apples",
            price: 120,
            images: ["/Banner/apple.jpeg"],
            features: ["Rich in fiber", "Boosts immunity", "Good for digestion"],
            inStock: true
      },
      {
            id: 2,
            name: "Bananas",
            description: "Ripe bananas full of energy",
            price: 60,
            images: ["/Banner/banana.jpg"],
            features: ["High in potassium", "Instant energy", "Good for heart health"],
            inStock: true,  
      },
      {
            id: 3,
            name: "Carrots",
            description: "Crunchy and healthy carrots",
            price: 80,
            images: ["/Banner/carrot.jpg"],
            features: ["Rich in Vitamin A", "Good for eyesight", "Low calorie snack"],
            inStock: true,  
      },
      {
            id: 4,
            name: "Tomatoes",
            description: "Farm fresh red tomatoes",
            price: 50,
            images: ["/Banner/tomato.jpg"],
            features: ["Rich in antioxidants", "Supports skin health", "Boosts immunity"],
            inStock: true,  
      },
      {
            id: 5,
            name: "Spinach",
            description: "Green leafy spinach full of iron",
            price: 40,
            images: ["/Banner/spinach.jpg"],
            features: ["High in iron", "Rich in vitamins", "Good for blood health"],
            inStock: true,  
      },
      {
            id: 6,
            name: "Onions",
            description: "Fresh white onions",
            price: 35,
            images: ["/Banner/onion.jpg"],
            features: ["Boosts metabolism", "Improves heart health", "Rich in antioxidants"],
            inStock: true,
      },
      {
            id: 7,
            name: "Potatoes",
            description: "Farm fresh potatoes",
            price: 25,
            images: ["/Banner/potato.jpg"],
            features: ["High in carbs", "Versatile cooking use", "Good energy source"],
            inStock: true,
      },
      {
            id: 8,
            name: "Bell Peppers",
            description: "Colorful bell peppers",
            price: 90,
            images: ["/Banner/bellpepper.jpg"],
            features: ["Rich in Vitamin C", "Low calorie", "Boosts immunity"],
            inStock: true,
      },
];

const mobileAccessories = [
      {
            id: 1,
            name: "boAt Power Bank",
            price: 1099,
            images: ["/Banner/power1.jpg"],
            features: ["10,000mAh capacity", "Fast charging", "Compact design"],
            inStock: true,
      },
      {
            id: 2,
            name: "Ambrane Power Bank",
            price: 1399,
            images: ["/Banner/power2.jpg"],
            features: ["20,000mAh capacity", "Dual USB output", "Lightweight"],
            inStock: true,
      },
      {
            id: 3,
            name: "Realme Buds",
            price: 799,
            images: ["/Banner/ear1.jpg"],
            features: ["Deep bass", "Long battery life", "Comfortable fit"],
            inStock: true,
      },
      {
            id: 4,
            name: "Redmi Earbuds",
            price: 999,
            images: ["/Banner/ear2.jpg"],
            features: ["Noise cancellation", "Sweat resistant", "Bluetooth 5.0"],
            inStock: true,
      },
      {
            id: 5,
            name: "Spigen Mobile Cover",
            price: 599,
            images: ["/Banner/cover1.jpg"],
            features: ["Shockproof", "Slim design", "Scratch resistant"],
            inStock: true,
      },
      {
            id: 6,
            name: "Ringke Mobile Cover",
            price: 499,
            images: ["/Banner/cover2.jpg"],
            features: ["Durable", "Matte finish", "Perfect grip"],
            inStock: true,
      },
      {
            id: 7,
            name: "Samsung Charger",
            price: 899,
            images: ["/Banner/charger1.jpg"],
            features: ["25W fast charging", "Type-C", "Compact size"],
            inStock: true,
      },
      {
            id: 8,
            name: "Anker Charger",
            price: 1299,
            images: ["/Banner/charger2.jpg"],
            features: ["Quick charge", "Dual port", "Durable build"],
            inStock: true,
      },
];

const electronics = [
      {
            id: 1,
            name: "Smart TV",
            price: 24999,
            images: ["/Banner/tv1.jpg"],
            features: ["4K Ultra HD", "Smart OS", "Multiple HDMI ports"],
            inStock: true,
      },
      {
            id: 2,
            name: "Bluetooth Speaker",
            price: 1999,
            images: ["/Banner/speaker1.jpg"],
            features: ["Rich bass", "Portable", "10-hour battery life"],
            inStock: true,
      },
      {
            id: 3,
            name: "Laptop",
            price: 49999,
            images: ["/Banner/laptop1.jpg"],
            features: ["Intel i5", "8GB RAM", "512GB SSD"],
            inStock: true,
      },
      {
            id: 4,
            name: "Headphones",
            price: 1499,
            images: ["/Banner/headphone1.jpg"],
            features: ["Noise cancellation", "Wireless", "Comfortable padding"],
            inStock: true,
      },
      {
            id: 5,
            name: "Smart Watch",
            price: 2999,
            images: ["/Banner/watch1.jpg"],
            features: ["Heart rate monitor", "Step tracking", "Water resistant"],
            inStock: true,
      },
      {
            id: 6,
            name: "Gaming Console",
            price: 39999,
            images: ["/Banner/console1.jpg"],
            features: ["4K gaming", "Wireless controller", "Exclusive titles"],
            inStock: true,
      },
];

const homeKitchen = [
      {
            id: 1,
            name: "Mixer Grinder",
            price: 2599,
            images: ["/Banner/mixer.jpg"],
            features: ["750W motor", "3 jars", "Durable build"],
            inStock: true,
      },
      {
            id: 2,
            name: "Non-Stick Pan",
            price: 899,
            images: ["/Banner/pan.jpg"],
            features: ["Scratch resistant", "Non-stick coating", "Even heating"],
            inStock: true,
      },
      {
            id: 3,
            name: "Dinner Set",
            price: 1999,
            images: ["/Banner/dinner.jpg"],
            features: ["24 pieces", "Microwave safe", "Elegant design"],
            inStock: true,
      },
      {
            id: 4,
            name: "Electric Kettle",
            price: 1499,
            images: ["/Banner/kettle.jpg"],
            features: ["1.5L capacity", "Auto cut-off", "Stainless steel"],
            inStock: true,
      },
      {
            id: 5,
            name: "Storage Box",
            price: 499,
            images: ["/Banner/storage.jpg"],
            features: ["Airtight", "Durable plastic", "BPA free"],
            inStock: true,
      },
      {
            id: 6,
            name: "Cooker",
            price: 1999,
            images: ["/Banner/cooker.jpg"],
            features: ["5L capacity", "ISI certified", "Aluminium body"],
            inStock: true,
      },
];

const fashion = [
      {
            id: 1,
            name: "Men's T-Shirt",
            price: 499,
            images: ["/Banner/tshirt.jpg"],
            features: ["100% cotton", "Regular fit", "Machine washable"],
            inStock: true,
      },
      {
            id: 2,
            name: "Women's Dress",
            price: 999,
            images: ["/Banner/dress.jpg"],
            features: ["Polyester blend", "Slim fit", "Party wear"],
            inStock: true,
      },
      {
            id: 3,
            name: "Jeans",
            price: 799,
            images: ["/Banner/jeans.jpg"],
            features: ["Denim fabric", "Slim fit", "Stretchable"],
            inStock: true,
      },
      {
            id: 4,
            name: "Wrist Watch",
            price: 1999,
            images: ["/Banner/watch2.jpg"],
            features: ["Analog display", "Water resistant", "Leather strap"],
            inStock: true,
      },
      {
            id: 5,
            name: "Sneakers",
            price: 1599,
            images: ["/Banner/shoes.jpg"],
            features: ["Lightweight", "Rubber sole", "Trendy design"],
            inStock: true,
      },
      {
            id: 6,
            name: "Handbag",
            price: 1299,
            images: ["/Banner/bag.jpg"],
            features: ["Spacious", "PU leather", "Durable handles"],
            inStock: true,
      },
];

const toys = [
      {
            id: 1,
            name: "Teddy Bear",
            price: 499,
            images: ["/Banner/teddy.jpg"],
            features: ["Soft plush", "Safe for kids", "Washable"],
            inStock: true,
      },
      {
            id: 2,
            name: "Building Blocks",
            price: 799,
            images: ["/Banner/blocks.jpg"],
            features: ["100+ pieces", "Creative play", "Durable plastic"],
            inStock: true,
      },
      {
            id: 3,
            name: "Remote Car",
            price: 1299,
            images: ["/Banner/car.jpg"],
            features: ["Rechargeable", "High speed", "Durable body"],
            inStock: true,
      },
      {
            id: 4,
            name: "Puzzle Game",
            price: 399,
            images: ["/Banner/puzzle.jpg"],
            features: ["500 pieces", "Brain exercise", "Fun for family"],
            inStock: true,
      },
      {
            id: 5,
            name: "Doll",
            price: 699,
            images: ["/Banner/doll.jpg"],
            features: ["Fashion doll", "Changeable outfits", "Safe materials"],
            inStock: true,
      },
      {
            id: 6,
            name: "Action Figure",
            price: 899,
            images: ["/Banner/action.jpg"],
            features: ["Articulated joints", "Collectible", "Durable plastic"],
            inStock: true,
      },
];

export { freshProducts, mobileAccessories, electronics, homeKitchen, fashion, toys };

export const allProducts = [
      ...freshProducts,
      ...mobileAccessories,
      ...electronics,
      ...homeKitchen,
      ...fashion,
      ...toys,
];
